### ISSUE TITLE
states: RUN: seems redundant

### ISSUE THREAD

**Issue by willr3** [RedHatPerf/qDup#1]
```YAML
states:
  RUN:
    key : value
    host:
      key : value  
```
The default scope for `key : value` pairs should be RUN and we should not have to specify RUN key. Keys's without values would then be either the RUN reserved word or the name of a host. 
Propesed new confiugration
```YAML
states:
  key : value #defaults to RUN scope
  host:
    key : valueh
```
The old method of declaring RUN can still be supported for existing scripts
