### ISSUE TITLE
Host configuration for multiple interfaces

### ISSUE THREAD

**Issue by johnaohara** [RedHatPerf/qDup#18]
Hosts often have multiple network interfaces and not all interfaces are visible to the script host.  In order to keep configuration limited to the qDup script, the scripts need to be able to update assets with configuration  defined in the qDup script.  Currently, the hosts are defined on a one-to-one mapping to interface, e.g.
```
hosts:
  client2: benchuser@benchclient2.perf.lab.eng.rdu.redhat.com:22
```
For multiple interfaces for each host, we could define the host resources as;
```
hosts:
  client1:
    - user: benchuser
    - port: 22
    - interfaces:
      - public: benchclient1.perf.lab.eng.rdu.redhat.com
      - priv: benchclient1.perf.lab.eng.rdu.redhat.com
      - G1: benchclient1.perf.lab.eng.rdu.redhat.com
      - G2: benchclient1G2 / 192.168.2.20
```
qDup could resolve host interfaces in scripts such as `${{client1.public}}` or `${{client1.G1}}` would map to the correct interface for state variable
