### ISSUE TITLE
For-Each does not work correctly

### ISSUE THREAD

**Issue by johnaohara** [RedHatPerf/qDup#25]

**Comment by johnaohara** [comment]
```
  testForEachExplicit:
    - for-each: SERVICE 'service1, service2, service3'
        sh: echo "testForEach - ${SERVICE}"
```
split into:

> split = {ArrayList@4567}  size = 1
 0 = "'service1, service2, service3"

and
```
  testForEach:
    - for-each: SERVICE ${{SERVICES}}
      sh: echo "testForEach - ${SERVICE}"
...
      - testForEach:
          with:
            SERVICES: serviceA, serviceB, serviceC
```
split into: 

> split = {ArrayList@4593}  size = 2
>  0 = "serviceA"
>  1 = "serviceB, serviceC"
> 
>
