### ISSUE TITLE
Intermittent failure of watch -> regex

### ISSUE THREAD

**Issue by johnaohara** [RedHatPerf/qDup#27]
The faban core script sometimes fails to match the `regex: "Killing benchmark"` from the faban log.  The run then hangs descite the run completing

**Comment by willr3** [comment]
I think the issue is `ctrlC` being sent to the terminal connection but the command on the server somehow does not respond to the SIGINT. I know it was sent to the terminal connection because I traced the ssh connection to file `--trace benchserver4` which creates a local temp file `/tmp/userName@hostName:portNumber and I can see the ^C at the end but the command is still running in `curl http://hostName:31337/active`
Do we want to add other SIG* options like SIGQUIT (`ctrl+\`) and SIGKILL (`ctrl+U`)? This would let us escalate killing a process just like in a real terminal connection:
```yaml
- sh: doSomethingForever.sh
  watch:
  - regex: FAIL
    then:
    - ctrlC # send SIGINT
    - sleep: 5s # give SIGINT 5 seconds to work
    - ctrlU # send SIGKILL
```
But to use this we would have to make sure `doSomethingForever.sh` is still running before calling `ctrlU`. I can think of a few options 

1. Change watchers to only run if the the parent `Cmd` is still active.
Right now all watchers run on all inputs for the command so this change would make watcher ordering much more important.
2. Add a new `Cmd` that checks if the parent `Cmd` is still active. This already exists inside qDup for some internal functionality so it would just need a convenient yaml name
3. Inspect the Cmd Tree and find all `ctrlX` under a `watch` or `on-signal` or `timeout` and make them only run if the parent `Cmd` is still active.


I think option 3 sounds best. I want qDup to stay as close to "what would you do when using multiple terminals yourself" and I don't want to introduce edge cases where the last line of output isn't seen by all watchers because the `ctrlC` watcher was first. 

Thoughts?

**Comment by willr3** [comment]
I made the changes for option 3 and added `ctrlU`+ `ctrl\` but it looks like the options from `stty -a` are not all accepted. Only `ctrlC` was able to stop a test process `./bin/standalone.sh` in my terminal so I will remove `ctrlU` and `ctrl/`.
Now `ctrlC` in a `watch` `on-signal` or `timeout` will only be sent if the observed `Cmd` is still active.
Should `ctrlC` retry until the observed `Cmd` returns the prompt (with a default wait time that can be configured)? The other option is explicitly retrying `ctrlC`
```yaml
- sh: doSomethingForever.sh
  watch:
  - regex: FAIL
    then:
    - ctrlC
    - sleep: 5s
    - ctrlC # will only run if doSomethingForever.sh is still running
```
I don't like the idea of qDup `Cmd` doing things automatically because it feels like it makes qDup more than just coordinated shell scripts but I can see where we expect sending `ctrlC` to work.
