### ISSUE TITLE
Regexp does not match line endings

### ISSUE THREAD

**Issue by rvansa** [RedHatPerf/qDup#7]
In script I had
```yaml
- sh: test ... && echo 'SUCCESS'
  - regex: ^SUCCESS$
    - signal: DONE
```
but despite I've seen SUCCESS line in the console the regexp was not matched. I've tried `'^SUCCESS$' ` and `"^SUCCESS$"` too but without success...

**Comment by rvansa** [comment]
Btw for these cases, `exitStatus` would be convenient:
```yaml
- sh: test ...
  - exitStatus: 0
    -signal: DONE
```

**Comment by willr3** [comment]
I suspect the `^...$` issue is that qDup gets the entire terminal output including the leading and trailing \r?\n (from most terminals). I see 3 options:
1. remove ^\r?\n and \r?\n$ from the Sh output
2. change Regex to remove the \r?\n when the pattern uses ^ or $
3. leave Regex and the input alone and change the patterns 

I implemented option 1 for now, do you think we should instead use a different one?

`exitStatus` is an interesting idea. Right now all of the qDup syntax is command independent. We can use `watch:` and `with:` and `timeout:` on any command (I agree they make the most sense on `sh`). Adding exitStatus would only work as a child of `sh` but it is the most common command so it would probably be a nice syntax alternative to:
```yaml
- sh: test ...
  - sh: echo $?  # prints the previous command exitStatus 
    - regex: ^0$ # match the 0 
      - signal: DONE
```   
I suspect we will also want to be able to handle multiple exitStatus checks?
```yaml
- sh: test ...
  - exitStatus: 0
    - singal: DONE
  - exitStatus: 2
    - abort:
```
