### ISSUE TITLE
For-each keeps looping if it's the last command in script

### ISSUE THREAD

**Issue by rvansa** [RedHatPerf/qDup#8]
```yaml
- sh: oc get pods --show-all=false -o name | cut -d "/" -f2
      - for-each: podName
         - sh: oc logs ${{podName}} -c `echo ${{podName}} | cut -d "-" -f 1` > /tmp/${{podName}}.log
```
was looping indefinitely (with empty `podName`) when it was the last thing in the script (skip was set to the `oc logs`). Adding `- sh: echo DONE` helped as workaround.
